### ISSUE TITLE
add logic to bump build number or calver on bot PRs

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/pangeo-dask-feedstock#15]
https://github.com/conda-forge/pangeo-dask-feedstock/pull/14/files 

@jhamman Would be nice to change pangeo-bot PR titles from `Update pangeo-dask metapackage version(s)` to `Updated distributed =2.15.2, dask=X, dask-gateway=X` for easy referencing.

currently we get automatic updates with new version (`distributed =2.15.2`), but don't update `{% set version = "2020.05.01" %}` or ` number: 1` if the date hasn't changed.

```yaml
{% set version = "2020.04.28" %}

package:
  name: pangeo-dask
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - dask =2.15.0
    - distributed =2.15.1
    - dask-kubernetes =0.10.1
    - dask-gateway =0.7.1
```
